# Generated by Django 4.1.4 on 2022-12-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'invalid': 'Такой Заголовок уже есть'}, max_length=50, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание Новости')),
                ('fail_path', models.TextField(null=True, verbose_name='Путь файлов')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Список новостей',
                'ordering': ['-published'],
            },
        ),
    ]
