# Generated by Django 4.1.4 on 2023-01-25 12:52

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
                ('description', models.TextField(error_messages={'null': 'Поле не заполнено'}, max_length=100, null=True, verbose_name='Описание рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'Такой Заголовок уже есть'}, max_length=50, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(error_messages={'null': 'Поле не заполнено'}, verbose_name='Описание Новости')),
                ('tag_news', models.CharField(max_length=100, null=True, verbose_name='Ключевые слова')),
                ('file_path', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='news_img', verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news_output.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Список новостей',
                'ordering': ['-published'],
                'get_latest_by': 'published',
            },
        ),
    ]
