# Generated by Django 4.1.4 on 2022-12-23 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_output', '0002_rubric_news_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Список новостей'},
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('title', 'description'), name='news_output_news_title_description_constraint'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
