# Generated by Django 4.1.4 on 2023-01-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0002_subrubric_superrubric_remove_rubric_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='superrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Надрубрика', 'verbose_name_plural': 'Надрубрики'},
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
