# Generated by Django 4.1.4 on 2022-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0003_advuser_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(error_messages={'null': 'Поле не заполнено'}, verbose_name='Описание Новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(error_messages={'unique': 'Такой Заголовок уже есть'}, max_length=50, unique=True, verbose_name='Заголовок'),
        ),
    ]
