# Generated by Django 4.1.4 on 2023-01-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0003_alter_superrubric_options_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubric',
            options={'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'), 'verbose_name': 'Подрубрика', 'verbose_name_plural': 'Подрубрики'},
        ),
    ]
