# Generated by Django 4.1.4 on 2023-01-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0004_alter_subrubric_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='rubric',
        ),
    ]
