# Generated by Django 4.1.4 on 2022-12-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0004_alter_news_description_alter_news_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='news',
            name='news_output_news_title_description_constraint',
        ),
    ]
