# Generated by Django 4.1.4 on 2023-01-29 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news_output.utilites


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_output', '0005_remove_news_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи'),
        ),
        migrations.AddField(
            model_name='news',
            name='rubric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='news_output.subrubric', verbose_name='Рубрика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='get_timestamp_path', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news_output.utilites.get_timestamp_path, verbose_name='Изображение')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_output.news', verbose_name='Обьявление')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация',
                'verbose_name_plural': 'Дополнительные иллюстрации',
            },
        ),
    ]
