# Generated by Django 4.1.4 on 2022-12-27 14:23

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0005_remove_news_news_output_news_title_description_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag_news',
            field=models.CharField(max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=markdownx.models.MarkdownxField(error_messages={'null': 'Поле не заполнено'}, verbose_name='Описание Новости'),
        ),
    ]
