# Generated by Django 4.1.4 on 2023-01-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0006_news_author_news_rubric_alter_news_file_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='file_path',
            new_name='image',
        ),
    ]
