# Generated by Django 4.1.4 on 2022-12-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0007_alter_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(error_messages={'null': 'Поле не заполнено'}, verbose_name='Описание Новости'),
        ),
    ]
