# Generated by Django 4.1.4 on 2023-02-04 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPublication',
            fields=[
            ],
            options={
                'verbose_name': 'Комментарий к статье',
                'verbose_name_plural': 'Комментарии к статьям',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_output.comment',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответы на комментарии',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news_output.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.comment', verbose_name='Автор Комментария к которому пишется ответ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.news', verbose_name='Обьявление'),
        ),
    ]
