# Generated by Django 4.1.4 on 2023-01-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0008_alter_news_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
