# Generated by Django 4.1.4 on 2023-01-12 13:04

import datetime
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0009_delete_advuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGSRoomReserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserving', django.contrib.postgres.fields.ranges.DateTimeRangeField(validators=[django.contrib.postgres.validators.RangeMinValueValidator(limit_value=datetime.datetime(2000, 1, 1, 0, 0)), django.contrib.postgres.validators.RangeMaxValueValidator(limit_value=datetime.datetime(3000, 1, 1, 0, 0))], verbose_name='Bpeмя резервирования')),
            ],
        ),
        migrations.AddField(
            model_name='rubric',
            name='description',
            field=models.TextField(blank=True, error_messages={'null': 'Поле не заполнено'}, max_length=100, verbose_name='Описание рубрики'),
        ),
    ]
