# Generated by Django 4.1.4 on 2023-02-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0010_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_comment',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Id главного родителя для веток комментов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.comment', verbose_name='Автор комментария к которому пишется ответ'),
        ),
    ]
