# Generated by Django 4.1.4 on 2023-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0011_comment_main_comment_alter_comment_target_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='main_comment',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Id главного родителя для веток комментов'),
        ),
    ]
