# Generated by Django 4.1.4 on 2023-01-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0011_alter_rubric_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGSRoomReserving',
        ),
    ]
