# Generated by Django 4.1.4 on 2023-01-12 13:20

import datetime
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0012_delete_pgsroomreserving'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGSRoomReserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserving', django.contrib.postgres.fields.ranges.DateTimeRangeField(validators=[django.contrib.postgres.validators.RangeMinValueValidator(limit_value=datetime.datetime(1900, 1, 1, 0, 0)), django.contrib.postgres.validators.RangeMaxValueValidator(limit_value=datetime.datetime(3000, 1, 1, 0, 0))], verbose_name='Bpeмя резервирования')),
            ],
        ),
    ]
