# Generated by Django 4.1.4 on 2023-02-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0013_alter_comment_main_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.news', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.comment', verbose_name='Автор комментария к которому пишется ответ'),
        ),
    ]
