# Generated by Django 4.1.4 on 2023-02-08 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_output', '0014_alter_comment_news_alter_comment_target_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='like_and_dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False, verbose_name='Лайки')),
                ('is_dislike', models.BooleanField(default=False, verbose_name='Дизлайки')),
                ('author', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь поставивший лайк')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.news', verbose_name='Статья к которой относиться лайк')),
                ('target_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_output.comment', verbose_name='комментарий к которому поставлен лайк')),
            ],
        ),
    ]
