# Generated by Django 4.1.4 on 2023-02-08 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_output', '0015_like_and_dislike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like_and_dislike',
            new_name='LikeDislike',
        ),
    ]
