# Generated by Django 4.1.4 on 2023-02-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0016_rename_like_and_dislike_likedislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedislike',
            options={'ordering': ['news__published'], 'verbose_name': 'Лайки и дизлайки', 'verbose_name_plural': 'Список лайков'},
        ),
    ]
