# Generated by Django 4.1.4 on 2023-01-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0016_alter_news_tag_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag_news',
            field=models.CharField(max_length=100, null=True, verbose_name='Ключевые слова'),
        ),
    ]
