# Generated by Django 4.1.4 on 2023-01-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0017_alter_news_file_path_alter_news_tag_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='file_path',
        ),
    ]
