# Generated by Django 4.1.4 on 2023-01-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0018_remove_news_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
