# Generated by Django 4.1.4 on 2023-01-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0019_news_file_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PGSRoomReserving',
        ),
    ]
