# Generated by Django 4.1.4 on 2023-01-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_output', '0020_delete_pgsroomreserving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file_path',
            field=models.ImageField(blank=True, null=True, upload_to='news_img', verbose_name='Изображение'),
        ),
    ]
