# Generated by Django 4.1.4 on 2023-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_auth_registered', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
