# Generated by Django 4.1.4 on 2023-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_auth_registered', '0003_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user_id', 'followers')},
        ),
    ]
