# Generated by Django 4.1.4 on 2023-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_auth_registered', '0004_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.IntegerField(verbose_name='подписка на пользователя ID'),
        ),
    ]
