# Generated by Django 4.1.4 on 2023-02-26 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_auth_registered', '0007_alter_follow_followers_alter_follow_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'диалог',
                'verbose_name_plural': 'Список диалогов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Содержание')),
                ('dialog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_auth_registered.dialog', verbose_name='Id Дилога к которому относиться сообщение')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_set', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Список сообщений',
            },
        ),
    ]
