# Generated by Django 4.1.4 on 2023-02-26 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_auth_registered', '0008_dialog_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': 'Список диалогов'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pub_date'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Список сообщений'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='author',
        ),
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата сообщения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_participant_one', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dialog',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_participant_two', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
